{% set version = "1.3.0" %}

package:
  name: configurable-http-proxy
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/jupyterhub/configurable-http-proxy/archive/{{ version }}.tar.gz
  sha256: 4c59c33a0db7b353d626691bd70763cdb7c5a97850cb3f0f01eb7111867fd9e3

build:
  number: 0
  script: npm install -g .

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - configurable-http-proxy -h

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD 3-Clause
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
