{% set name = "configurable-http-proxy" %}
{% set version = "4.1.0" %}
{% set build = 2 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 78c11e968534400f495b2374db976fbc89b2ee2fa3e6de67a85a45484646e3a6

build:
  number: {{ build }}
  string: "node{{ node }}_h{{ PKG_HASH }}_{{ build }}"
  script: npm pack; npm install -g {{name}}-{{version}}.tgz  # [not win]

requirements:
  host:
    - nodejs {{ node }}.*
  run:
    - nodejs {{ node }}.*

test:
  commands:
    - configurable-http-proxy -h

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD 3-Clause
  license_file: LICENSE
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
    - willingc
