{% set name = "configurable-http-proxy" %}
{% set version = "5.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jupyterhub/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2a8bda5a8fd42e4433e5be87de5ef539c96d1c75b5007bb7d7ceba14ba374b27

build:
  number: 0

requirements:
  build:
    - nodejs 24.*
  host:
    - nodejs 24.*
    - yarn 1.22.22
  run:
    # Prerequisite: Node.js ≥ 18 -> https://github.com/jupyterhub/configurable-http-proxy/blob/5.1.0/README.md#install
    # Used the latest available runtime version:
    - nodejs 24.*

# Unable to run tests, needs pipx(not in the main channel) to install internal SSL -> https://github.com/jupyterhub/configurable-http-proxy/blob/main/.github/workflows/test.yml#L84
test:
  commands:
    - configurable-http-proxy -h
    - test -f $PREFIX/bin/configurable-http-proxy  # [not win]
    - if not exist %PREFIX%\\configurable-http-proxy exit 1    # [win]

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: node-http-proxy plus a REST API
  description: |
    configurable-http-proxy (CHP) provides you with a way to update and manage a proxy table 
    using a command line interface or REST API. It is a simple wrapper around node-http-proxy. 
    node-http-proxy is an HTTP programmable proxying library that supports websockets and is 
    suitable for implementing components such as reverse proxies and load balancers. 
    By wrapping node-http-proxy, configurable-http-proxy extends this functionality to 
    JupyterHub deployments.
  dev_url: https://github.com/jupyterhub/configurable-http-proxy
  doc_url: https://github.com/jupyterhub/configurable-http-proxy/tree/main/README.md

extra:
  recipe-maintainers:
    - minrk
    - willingc
