{% set name = "configurable-http-proxy" %}
{% set version = "4.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 84d9cd8551e6a3204808ff5146491eaab4705f599e5630ee1618b53a3650a0cd

build:
  number: 0
  skip: true # [s390x]

requirements:
  build:
    - nodejs 18.*
  host:
    - nodejs 18.*
    - yarn 1.22.19
  run:
    - nodejs

test:
  commands:
    - configurable-http-proxy -h
    - test -f $PREFIX/bin/configurable-http-proxy  # [not win]
    - if not exist %PREFIX%\\configurable-http-proxy exit 1    # [win]

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: node-http-proxy plus a REST API
  description: |
    configurable-http-proxy (CHP) provides you with a way to update and manage a proxy table 
    using a command line interface or REST API. It is a simple wrapper around node-http-proxy. 
    node-http-proxy is an HTTP programmable proxying library that supports websockets and is 
    suitable for implementing components such as reverse proxies and load balancers. 
    By wrapping node-http-proxy, configurable-http-proxy extends this functionality to 
    JupyterHub deployments.
  dev_url: https://github.com/jupyterhub/configurable-http-proxy
  doc_url: https://github.com/jupyterhub/configurable-http-proxy

extra:
  recipe-maintainers:
    - minrk
    - willingc
