{% set version = "3.0.0" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}

package:
  name: configurable-http-proxy
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/jupyterhub/configurable-http-proxy/archive/{{ version }}.tar.gz
  sha256: 6573e2862830d0ba34ef51fef7c9a680dd064d92acc366bf382fc1a8100709fc

build:
  number: 0
  script: npm install -g .

requirements:
  build:
    - nodejs {{node_version}}
  run:
    - nodejs {{node_version}}

test:
  commands:
    - configurable-http-proxy -h

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD 3-Clause
  license_file: LICENSE
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
