travis:
  secure:
    BINSTAR_TOKEN: RwQe2B0ZtkMxg3Em32/DJ24pJQrdlwKz0IXdAgL7Obxx9yN6wRRXy37nPdRxzQ5GkRRIO4BlHprhhiM3Y9ASTZvBESx8iE2wqNZNbLfK/Jjo0ZdBNLYayLAlXOVqmcj2HQtUs8ODS8uEDIp2yOFeV//Crdt/trulxoi8kC/3bt+FCKzIy9kJSdhCJzuz7N+O1LuiPBAUIaqUZ+UWQIDHaGrJdBpDk4M9+sgEp6t6f1r9HRKgKsppOTcQv0K1KnJKmvsXu6QebRdudHoaSj/Yghc3R3bLATpVw8ZK+7QNWZSOV16zB78wDHxMeTcYaHFM7ZrcFM8FbF2M82tIgKYWnGGHePuREhEJ90aQW/GwTNCXlAMl3ArjZGnZO3vnvsyHucLEbvs/onwf6sH4MUIe2l7eR8fkX3U3rrufar1zNxKA8qTF6hQh9lFdJbjUnPkVD1qWo5IgGfl5t3Kwa+xU4Nio0ptqdE0z0tkTXSzz/I1KxSBQRXCb8TvDFZ90s4KsCIdhEpraEfbZDPqJwGnuhO9LRhEqVZNG8mbGBMvICacWRX7cUJm1O9MkWz0nev7iJ/0SUi+nwwW12KuZ1YQTAtiWuNysR+86fC2V82Cofy8pAGJ1U5/R30UCHbCJKZFebdUj08pY8WnWBqwUHtFtZQUcwa9x44L5nuRqu+BAzOo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
