travis:
  secure:
    BINSTAR_TOKEN: GmOEHOa3d4yN8/r/SmNbT47mm+GOhsIwmCJm1s4esIa6IYSWbiz4/hrBobqp3vlLSvk//QFwMCoXxzG9JbxMksyJ4CJ6a3JK+wN4b+I0/3uvYBfcuzM8ju9VkoWDAGX9g+HzJuHmrMviLLkwwA5f4UrtyM5nrVxEW1tTu6a70XkukLs0RPU10qq/i8YqxhNRiVEfTS8Q3ZuFQnc8MpgDbuRqhLIBEkavpPvmqh+/9eV7mpjePrTpSFh74IVoluAhOw8LuqJVIEjkPcdQMZ362pvHsU6ClxxSmmX6b5sc5t8WAmNpbSf750saABGk9e+5z3ZWeda/0e5IHqYdwHlELPEVCHzJrjqEc+eR4xwQANXEA1bfQtgiDk6CgUQSzmxNUdLQLOBot3qDTyB+kP6uDXvqLDx1O+MMr5ThNVSipj97U2GSWtWRJS9U8SvDOMCRTdqcv0N7w6034bXYcaqRAtsduWkdnZetT4+YOhq7dLzHysyO3nDsEAl3chnkWxMM8APNCaHSFUbfo1dZtChxfB4BwmLQziZ5yvMweIr/B2teqpQuuGVVxN55wENEI8AFPaSS4st7ux+Mf3ETafvL3t1LHo2M5bere0FM+aSUJSV6BVL/4b8RhAGJvwJPRLNq7IjfPRp/GdZ4Mve3FwXHTKNpeOpZUaUiHd2tyh8W4R4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {linux_aarch64: default, win: azure}
